stages:
  - Generate
  - Build
  - Deploy


generate-docs:
  image: nicklehmann/poetry:py3.8-preview-alpine
  stage: Generate
  before_script:
    - apk add build-base
    - poetry install
  script:
    - invoke docs
  artifacts:
    paths:
      - dist/docs

build-doc:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: Build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR/
      --dockerfile $CI_PROJECT_DIR/docs/Dockerfile
      --destination $CI_REGISTRY_IMAGE/docs

deploy-doc:
  image: alpine/helm:3.0.2
  stage: Deploy
  environment:
    name: Contabo
    url: https://generi.nicklehmann.sh
  variables:
    HELM_RELEASE: generi-docs
    HELM_NAMESPACE: generi
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
  script:
    - helm delete -n $HELM_NAMESPACE $HELM_RELEASE || true
    - helm install -n $HELM_NAMESPACE -f docs/deploy.yaml $HELM_RELEASE bitnami/nginx
